# Makefile.deps created Tue Feb  2 18:16:32 PST 2010
interp.o: interp.cc interp.h object.h numbers.h trace.h util.h
main.o: main.cc interp.h object.h numbers.h trace.h util.h
numbers.o: numbers.cc numbers.h trace.h util.h
object.o: object.cc object.h numbers.h trace.h util.h
trace.o: trace.cc trace.h
util.o: util.cc util.h trace.h
